# -*- mode: ruby -*-
# vi: set ft=ruby :

# vagrant up --provider=docker
# vagrant ssh -L 9200:localhost:9200
# vagrant ssh -- -L 9901:localhost:9201 -L 9000:localhost:9200 -L 5602:localhost:5601 -L 5603:localhost:5602 -L 5672:localhost:5672 -L 15672:localhost:15672 -L 5432:localhost:5432 -L 8080:localhost:8080 -L 8081:localhost:8081


Vagrant.configure(2) do |config|

    # ... your existing config
    config.vm.box = "ubuntu/trusty64"
     config.vm.network "private_network", ip: "192.168.33.12"
    # config.vm.network "public_network"
    #  config.vm.network "forwarded_port", guest: 90, host: 9200
    config.vm.network "forwarded_port", guest: 9201, host: 9201
    
     #  config.vm.provision "shell", path: "provision.sh"
    
     config.vm.provision :docker
     # config.vm.synced_folder "/Users/euiyoung.hwang/repos/", "/home/vagrant/projects"
     config.vm.synced_folder "C:\\Users\\euiyoung.hwang\\Git_Workspace\\", "/home/vagrant/projects"
     config.vm.provider "virtualbox" do |vb|
    #     vb.memory = "8192"
        vb.memory = "10240"
     end
    
     # config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
     # config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    #  config.vm.provision "file", source: "~/.ssh/id_ed25519", destination: "~/.ssh/id_ed25519"
    #  config.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "~/.ssh/id_ed25519.pub"
    
      # Custom configuration for docker
      config.vm.provider "docker" do |docker, override|
        # docker doesnt use boxes
        override.vm.box = nil
    
        # this is where your Dockerfile lives
        docker.build_dir = "."
    
        # Make sure it sets up ssh with the Dockerfile
        # Vagrant is pretty dependent on ssh
        override.ssh.insert_key = true
        docker.has_ssh = true
    
        # Configure Docker to allow access to more resources
        docker.privileged = true
      end
    
    # ...
    
    end