---
client:
  hosts:
    - localhost
  port: 9200
  url_prefix:
  use_ssl: False
  certificate: /home/biadmin/utils/curator-config-dev/root-ca.pem
  client_cert: /home/biadmin/utils/curator-config-dev/kirk.pem
  client_key: /home/biadmin/utils/curator-config-dev/kirk-key.pem
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']

